### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by GalackQSM** [discordextremelist/website#132]
C:\Users\cynthia\Desktop\website-master>npm run start

> del-website@5.2.8-Release start C:\Users\cynthia\Desktop\website-master
> node dist/src/app

C:\Users\cynthia\Desktop\website-master\node_modules\datadog-metrics\lib\reporters.js:29
        throw new Error('DATADOG_API_KEY environment variable not set');
        ^

Error: DATADOG_API_KEY environment variable not set
    at new DataDogReporter (C:\Users\cynthia\Desktop\website-master\node_modules\datadog-metrics\lib\reporters.js:29:15)
    at new BufferedMetricsLogger (C:\Users\cynthia\Desktop\website-master\node_modules\datadog-metrics\lib\loggers.js:41:38)
    at Object.init (C:\Users\cynthia\Desktop\website-master\node_modules\datadog-metrics\index.js:27:20)
    at Object.<anonymous> (C:\Users\cynthia\Desktop\website-master\dist\src\Util\Services\discord.js:49:9)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! del-website@5.2.8-Release start: `node dist/src/app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the del-website@5.2.8-Release start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cynthia\AppData\Roaming\npm-cache\_logs\2020-09-07T22_54_44_779Z-debug.log

Screen : https://prnt.sc/udaljj

**Comment by advaith1** [comment]
Looks like you didn't set the datadog api key in settings.json

however, we do not support making your own bot list as a clone of DEL; you can do it as long as you follow the license, but we will not help you.

**Comment by Cairo2k18** [comment]
Isn't a bug, you need to figure this one out yourself mate, we don't provide self hosting support.

**Comment by Cairo2k18** [comment]
The site is only intended to run on our own infrastructure and for development using our settings, self hosting it for commercial use will likely not work.
